### ISSUE TITLE
AMOR DESBLOQUEAME YA CAMBIE

### ISSUE THREAD

**Issue by mavillan** [mosoriob/ckan-tacc-images#2]
TE LO JURO YA CAMBIE

**Comment by mosoriob** [comment]
MENTIRA, USASTE NUESTRO AUTO PARA ANDAR CON ELLA

**Comment by mavillan** [comment]
HAZLO POR NUESTRO CHIQUITO, JULIANCITO TE EXTRAÑA :(

**Comment by mosoriob** [comment]
![IMG_1135](https://github.com/user-attachments/assets/44d3ed73-9e91-4735-92e8-3c4993917311)
PAGAME LA PENSION. NOS VEMOS EN TRIBUNALES
